<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>com.joao.depguard</groupId>
    <artifactId>depguard-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>DepGuard</name>
    <description>Suíte DevSecOps: dependências vulneráveis + segredos + SBOM</description>

    <properties>
        <java.version>17</java.version>
        <picocli.version>4.7.5</picocli.version>
        <cyclonedx.version>12.2.0</cyclonedx.version>
    </properties>

    <modules>
        <module>depguard-core</module>
        <module>depguard-cli</module>
        <module>depguard-server</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- módulo interno: versão única em um lugar só -->
            <dependency>
                <groupId>com.joao.depguard</groupId>
                <artifactId>depguard-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli</artifactId>
                <version>${picocli.version}</version>
            </dependency>

            <dependency>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-core-java</artifactId>
                <version>${cyclonedx.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
